### ISSUE TITLE
Heading, Input Fields and List of activities

### ISSUE THREAD

**Issue by Ava-VictoriaCrivello** [Ava-VictoriaCrivello/Capstone-Projekt#1]
## Value Proposition

**As a**  user
**I need** a form
**to be able to** add new activities
## Description

<img width="610" alt="Screenshot 2022-07-15 at 12 39 20" src="https://user-images.githubusercontent.com/95885504/179207683-0f449fb1-03e8-44dc-80be-fed878a0e1ef.png">

## Acceptance Criteria

- [ ] Activity must be able to be specified
- [ ] Start time and end time must be able to be specified
- [ ] After submit, the entered data are added to the list below the form
- [ ] Listing of the dates under the input fields
- [ ] Latest newest displayed on top
- [ ] the List is scrollable

## Tasks

(for developers team)

- [ ] Global Styles
- [ ] component/ Heading
- [ ] component/ Card with input Fields
- [ ] All 3 input fields are required
- [ ] component/ Form
- [ ] Create form.js 
- [ ] Storybook
- [ ] Write tests
- [ ] Add to App

**Comment by PReichetanz** [comment]
Hello Ava,

nice work! This is a good starting point for your first user story! 🎉

I have some ideas we might discuss: 💬

## Value Proposition
- grammar: delete the three dots and write "user" lowercase
- Don't describe all components here, but the general purpose: `**I need** a form **to be able to** add new activities`.

## Description
- Where do you place your labels?

## Acceptance Criteria
Really good! Maybe rewrite the third point to "After submit, the entered data are added to the list below the form." or similar.

## Tasks
- Do you want to create a component for the form as well?

**Comment by PReichetanz** [comment]
Hi Ava,

really nice refactoring!

Just two things:
- You do not have labels in your wireframe (it looks like placeholders right now), so where do you want to place the labels?
- Are all input fields required? If so, that's an acceptance criteria you need to mention.
