### ISSUE TITLE
Delete function 

### ISSUE THREAD

**Issue by Ava-VictoriaCrivello** [Ava-VictoriaCrivello/Capstone-Projekt#2]
## Value Proposition

**As a**  user
**I need**  delete button
**to be able to** delete entries again

## Description
<img width="200" alt="Screenshot 2022-07-15 at 12 46 35" src="https://user-images.githubusercontent.com/95885504/179208738-fe4296e5-c972-4a56-bfd4-bb576a817710.png">

## Acceptance Criteria

- [ ]Clicking the delete button deletes the entry from the list
- [ ] all data should be combined in one field

(for developers team)

- [ ] component/ List entry
- [ ] Create delete Button with function
- [ ] Component for dates and delete function
- [ ] Storybook
- [ ] write Tests

**Comment by mbosselmann** [comment]
Hi Ava,
I like your user story! 👍 But I have some remarks that you should consider:

**Value Proposition**
"I need delete function, Component for the styling of list entries"
- Do you want to implement a component for list entries or a delete functionality? I think only the delete functionality or? 🤔 

**Acceptance Criteria**
- Why "..."?
- The styling of your other components has nothing to do with the delete functionality. Therefore, you should maybe make an extra user story for styling the app?

I hope this is helpful. Feel free to ask me if you have questions regarding my remarks. :)

**Comment by PReichetanz** [comment]
Hi Ava,

looks good so far! I would like to add some remarks:
- "I need a delete button / to be able to...": the other parts in the second line should not be part of the value proposition.
**Acceptance Criteria**
- Rephrase them so that you can check them afterwards:
- "Clicking the delete button deletes the entry from the list."

**Tasks**
- The GlobalStyles should already be implemented in the first story, so you don't have to add it here as well.
- Do you need components for dates and delete function or can you integrate them in the list entry component? I don't see where you can use these components again, but maybe there will be a useful part in your app.

**Comment by chris-yooo** [comment]
hey ava :)

a small thing with big impact please look that your buttons are accessible for developer tasks maybe

and you can leave out the add to app

chris

**Comment by actyvystom** [comment]
Hi Ava,
please take a close look on the feedback before: as @mbosselmann mentioned, you probably rather need a *delete functionality* that is triggered by a *delete button component* inside your todo list elements. Thinking this way might be a good hint to phrase your acceptance criteria then. Keep on, you are on a good way to the right user story ;)
Some minor format issues: your markdown checkboxes and list items are a bit mixed up, also your headline for the tasks has gone...
