### ISSUE TITLE
Dropdown Menü

### ISSUE THREAD

**Issue by Ava-VictoriaCrivello** [Ava-VictoriaCrivello/Capstone-Projekt#3]
## Value Proposition

**As a** user
**I need** a Dropdown Menü
**to be able to** create a separation of the dates

## Description
<img width="200" alt="Screenshot 2022-07-18 at 11 23 49" src="https://user-images.githubusercontent.com/95885504/179723040-d97464cc-1e08-448a-ac8c-bffbc6542af8.png">

## Acceptance Criteria

- [ ] Separation of appointments can be made via the dropdown menu
- [ ] Activities that are separated from each other are color-coded

## Tasks

(for developers team)

- [ ] Storybook
- [ ] Write Tests
- [ ] Component for one Record

**Comment by actyvystom** [comment]
Hi Ava, 
a nice one! :)
A few remarks to consider:
- I guess you want to point out that a user needs a way to categorize his date entries. 
   - That way of putting the value proposition, the dropdown menu (component) will get a part of the acceptance criteria and thus also a part of the tasks
- Please try to get more precise in explaining the tasks:
   -  Storybook (component) for which elements?
   - Tests for which elements?
   - It might be a better wording if you use _one component for every record/entry_ -> which is then almost identical to a _universal component for every category of date entries_ ;)
